### ISSUE TITLE
List current counter

### ISSUE THREAD

**Issue by dusterherz** [LeoDJ/telegram-counter-bot#1]
Hi,
Following the new update, we wanted to list all the counters but we doesn't find a command for it. It is possible to add one ?

**Comment by LeoDJ** [comment]
That is actually a really good idea, I'm currently trying to implement it right now

**Comment by LeoDJ** [comment]
I've successfully implemented it. It's not thoroughly tested, but so is everything else 😜 

I'm also planning to add label management to the bot in the future, but not right now 😉
