### ISSUE TITLE
Increment by x

### ISSUE THREAD

**Issue by Peter42** [LeoDJ/telegram-counter-bot#4]
Ability to increment the counter by x.
Proposed solution: Add an optional argument to `/inc` (while `/inc` still increments the counter by one e.g. `/inc 5` increments the counter by five).
Same for `/dec`.

_Let me known if you want me to implement it._

**Comment by LeoDJ** [comment]
Implemented in https://github.com/LeoDJ/telegram-counter-bot/commit/64641dacf7fa9883e9fdbcd273c97e1eaf6d8cee
